/**
 * CommentaryCard — renders the LLM-generated commentary on the detail page.
 *
 * The card is intentionally understated: a tiny "AI" badge, the body
 * text, and a small "Generated by …" line. We don't try to look fancier
 * than a search result card — the value is in the text, not the chrome.
 */
import type { MusicAnalysis } from "@/types/audio";

interface CommentaryCardProps {
  analysis: MusicAnalysis;
}

function formatTimestamp(iso: string | null | undefined): string | null {
  if (!iso) return null;
  try {
    return new Date(iso).toLocaleString();
  } catch {
    return null;
  }
}

function modelLabel(model: string | null | undefined): string {
  if (!model) return "AI";
  if (model === "mock") return "AI (preview)";
  if (model === "openai-compatible") return "AI";
  // Show a short, friendly version of the model name.
  return `AI · ${model}`;
}

export function CommentaryCard({ analysis }: CommentaryCardProps) {
  const text = analysis.commentary;
  if (!text) {
    return (
      <div
        data-testid="commentary-empty"
        className="rounded-lg border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-500"
      >
        The AI commentary will appear here once the analysis finishes.
      </div>
    );
  }

  const ts = formatTimestamp(analysis.commentary_generated_at);

  return (
    <section
      data-testid="commentary-card"
      className="rounded-lg border border-indigo-100 bg-gradient-to-br from-indigo-50/60 to-white p-5"
    >
      <header className="mb-2 flex items-center gap-2">
        <span className="inline-flex items-center rounded-full bg-indigo-600 px-2 py-0.5 text-xs font-semibold uppercase tracking-wide text-white">
          {modelLabel(analysis.commentary_model)}
        </span>
        <h3 className="text-sm font-semibold text-slate-700">
          Take on this track
        </h3>
      </header>
      <p className="text-sm leading-6 text-slate-800">{text}</p>
      {ts && (
        <p className="mt-3 text-xs text-slate-400">Generated {ts}</p>
      )}
    </section>
  );
}
