/**
 * CommentaryCard --- renders the LLM-generated commentary on the detail page.
 *
 * The card is intentionally understated: a tiny "AI" badge, the body
 * text, and a small "Generated by ..." line. We don't try to look fancier
 * than a search result card --- the value is in the text, not the chrome.
 */
import { useTranslation } from "react-i18next";

import type { MusicAnalysis } from "@/types/audio";

interface CommentaryCardProps {
  analysis: MusicAnalysis;
}

function formatTimestamp(iso: string | null | undefined): string | null {
  if (!iso) return null;
  try {
    return new Date(iso).toLocaleString();
  } catch {
    return null;
  }
}

function modelLabel(
  model: string | null | undefined,
  t: (key: string) => string,
): string {
  if (!model) return t("detail.analysis.commentary.model");
  if (model === "mock") return t("detail.analysis.commentary.modelPreview");
  if (model === "openai-compatible") return t("detail.analysis.commentary.model");
  // Show a short, friendly version of the model name.
  return `${t("detail.analysis.commentary.model")} · ${model}`;
}

export function CommentaryCard({ analysis }: CommentaryCardProps) {
  const { t } = useTranslation();
  const text = analysis.commentary;
  if (!text) {
    return (
    <div
      data-testid="commentary-empty"
      className="rounded-lg border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-500 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-400"
    >
      {t("detail.analysis.commentary.empty")}
    </div>
  );
}

  const ts = formatTimestamp(analysis.commentary_generated_at);

  return (
    <section
      data-testid="commentary-card"
      className="rounded-lg border border-indigo-100 bg-gradient-to-br from-indigo-50/60 to-white p-5 dark:border-indigo-900/40 dark:from-indigo-950/20 dark:to-slate-900"
    >
      <header className="mb-2 flex items-center gap-2">
        <span className="inline-flex items-center rounded-full bg-indigo-600 px-2 py-0.5 text-xs font-semibold uppercase tracking-wide text-white">
          {modelLabel(analysis.commentary_model, t)}
        </span>
        <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-200">
          {t("detail.analysis.commentary.title")}
        </h3>
      </header>
      <p className="text-sm leading-6 text-slate-800 dark:text-slate-200">{text}</p>
      {ts && (
        <p className="mt-3 text-xs text-slate-400 dark:text-slate-500">
          {t("detail.analysis.commentary.generatedAt", { when: ts })}
        </p>
      )}
    </section>
  );
}
